export const GET_ALL_PEOPLE = 'GET_ALL_PEOPLE';
export const GET_ALL_OPPORTUNITIES = 'GET_ALL_OPPORTUNITIES';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const GET_ERRORS = 'GET_ERRORS';
export const CHANGE_TAB = 'CHANGE_TAB';
